### ISSUE TITLE
Unnamed types' constructors and destructors?

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/cpp_demangle#128]
#127 puts off unnamed types' constructors and destructors since I haven't seen a real symbol that has that yet. Would need to add another `LeafName` variant.

Running the following symbol through `c++filt`, `demangle.go`, and my system `__cxa_demangle`, I see what looks to be the same bug in `libiberty` as lambda constructors/destructors.

```rust
demangles!(
    _ZZ3aaavENUt_D1Ev,
    "aaa()::{unnamed type#1}::~{unnamed type#1}()"
);
```

**Comment by miguelsaldivar** [comment]
I think #168 closed this issue? :smile:

**Comment by fitzgen** [comment]
Good catch!
