### ISSUE TITLE
rust starting path name demangling

### ISSUE THREAD

**Issue by m4b** [gimli-rs/cpp_demangle#130]
E.g.:

```
echo '_ZN33_$LT$alloc..arc..Arc$LT$T$GT$$GT$9drop_slow17h9ed4cba808ccbc62E' | c++filt
<alloc::arc::Arc<T>>::drop_slow

echo '_ZN33_$LT$alloc..arc..Arc$LT$T$GT$$GT$9drop_slow17h9ed4cba808ccbc62E' | cppfilt 
_$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::h9ed4cba808ccbc62
```

Strangely, `c++filt` agrees with `cppfilt` on OSX :thinking: but has output as above on linux...

**Comment by tromey** [comment]
> Strangely, c++filt agrees with cppfilt on OSX 🤔 but has output as above on linux...

Maybe different versions?  Extra demangling for Rust was added here: https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=242524 - a year ago now, I guess.

**Comment by fitzgen** [comment]
Thanks for filing an issue, @m4b.

However, I don't intend to support demangling Rust symbols in this crate. There's already https://crates.io/crates/rustc-demangle for that, and it should be easy enough to make a wrapper crate that is the union of these two crates if one needed.
