### ISSUE TITLE
UnexpectedText when demangling main

### ISSUE THREAD

**Issue by SoftwareApe** [gimli-rs/cpp_demangle#180]
Reproduction:

    cpp_demangle 0.2.12
    Symbol::new(b"main"); // => Err(UnexpectedText)

I would expect a common non-mangled symbol to be returned as the same symbol.

**Comment by fitzgen** [comment]
Thanks for filing an issue.

`main` isn't a C++ mangled symbol, so it doesn't parse as one. If you want the non-mangled symbols returned as-is behavior, you can do something like this:

```rust
fn maybe_demangle(symbol: &str) -> Cow<str> {
    if let Ok(sym) = Symbol::new(symbol) {
        sym.to_string().into()
    } else {
        symbol.into()
    }
}
```

I don't think that this library for demangling mangled symbols should bake that behavior in, however.
