### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by benfred** [gimli-rs/cpp_demangle#181]
Thanks for this project! I'm a big fan, I've even written some basic python bindings for it: https://github.com/benfred/py-cpp-demangle. 

I'm wondering if we can get a new version pushed out to crates.io?

It's been almost a year since v0.2.12, and there have been a couple bug fixes since then. I'm particularly interested in getting https://github.com/gimli-rs/cpp_demangle/pull/159 into a public release.

I'm using this crate for demangling symbols from native python extensions in a [python profiler](https://github.com/benfred/py-spy/) I've been working on, and while this project (and all of Gimli) has been working out great - not having #159 frequently leads to some odd looking output.

**Comment by fitzgen** [comment]
Glad that this crate is working for you -- just published 0.2.13!

**Comment by benfred** [comment]
Awesome - thank you!
