### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by miguelsaldivar** [gimli-rs/cpp_demangle#196]
Can we cut a new release, @jan-auer added some fixes for `clone-suffixes` and asked for a release with the new changes. Do you think that could be possible @fitzgen? :)

**Comment by khuey** [comment]
I can look at doing a release this weekend.

**Comment by miguelsaldivar** [comment]
@khuey that's perfect, thank you! :+1:

**Comment by khuey** [comment]
I can't push the tag to Github yet but 0.2.15 is live on crates.io.
