### ISSUE TITLE
Ability to hide the return type?

### ISSUE THREAD

**Issue by mstange** [gimli-rs/cpp_demangle#201]
Hi,

I'm ending up with demangled names such as these ones:

 - `void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned short, float __vector(16)*, Texture&, int, Texture&, ClipRect const&)` (from mangled name: `_ZL15draw_quad_spansIjEviPN4glsl11vec2_scalarEtPDv16_fR7TextureiS6_RK8ClipRect`)
 - `void draw_elements<unsigned short>(int, int, Buffer&, unsigned long, VertexArray&, Texture&, int, Texture&)` (from mangled name: `_ZL13draw_elementsItEviiR6BuffermR11VertexArrayR7TextureiS5_`)
 - `int check_depth8<515, false>(unsigned short, unsigned short*, short __vector(8)&)` (from mangled name: `_ZL12check_depth8ILi515ELb0EEitPtRDv8_s`)
 - `decltype ((applyImpl)({parm#1}, {parm#2}, (*this).mArguments, std::__1::integer_sequence<unsigned long, (unsigned long)0, (unsigned long)1>{})) mozilla::detail::RunnableMethodArguments<mozilla::wr::WrWindowId, bool>::apply<mozilla::wr::RenderThread, void (mozilla::wr::RenderThread::*)(mozilla::wr::WrWindowId, bool)>(mozilla::wr::RenderThread*, void (mozilla::wr::RenderThread::*)(mozilla::wr::WrWindowId, bool))` (from mangled name: `_ZN7mozilla6detail23RunnableMethodArgumentsIJNS_2wr10WrWindowIdEbEE5applyINS2_12RenderThreadEMS6_FvS3_bEEEDTcl9applyImplfp_fp0_dtdefpT10mArgumentstlNSt3__116integer_sequenceImJLm0ELm1EEEEEEEPT_T0_`)

I would prefer to hide the return type. Especially in the last case it produces a lot of visual noise. Also, most symbols do not have a return type, so skipping return types for all symbols would make things more consistent and uniform.

What are your opinions on adding a flag to skip the return type?

**Comment by khuey** [comment]
Adding a flag to `DemangleOptions` and picking it up in `BareFunctionType`s `Demangle` impl seems fine.

**Comment by mstange** [comment]
I have a patch.
