### ISSUE TITLE
Breaking change in 0.2.17

### ISSUE THREAD

**Issue by Dfinity-Alin** [gimli-rs/cpp_demangle#204]
The `0.2.17` release [breaks `symbolic-demangle`](https://github.com/getsentry/symbolic/pull/244) because a new field was added to `DemangleOptions`. The release should be yanked and replaced with a `0.3.0` release.

**Comment by Dfinity-Alin** [comment]
A new `7.x` release of `symbolic-demangle` (`7.3.6`) was made to deal with this issue, but the `6.x` releases are still broken. (And `pprof` among other crates depends on `symbolic-demangle 6.x`, so it was not fixed by the new `7.3.6` release.)

**Comment by khuey** [comment]
Alright, 0.2.17 was yanked, 0.3.0 is published now, with some API changes to make it more future proof.

**Comment by jan-auer** [comment]
Thanks, @khuey!
