### ISSUE TITLE
Symbol::demangle fails to display parameters of some symbols

### ISSUE THREAD

**Issue by HadrienG2** [gimli-rs/cpp_demangle#270]
An fmt::Error will be emitted by Symbol::demangle upon trying to display the following symbols

```
_ZN4Acts11MeasurementINS_4Test25ExtendedMinimalSourceLinkEJLNS_22BoundParametersIndicesE0EEEC2IJEEESt10shared_ptrIKNS_7SurfaceEERKS2_N5Eigen6MatrixIdLi1ELi1ELi0ELi1ELi1EEENSt9enable_ifIXeqplsZT_Li1EsZT0_EdE4typeEDpT_
_ZN4Acts11MeasurementINS_4Test25ExtendedMinimalSourceLinkEJLNS_22BoundParametersIndicesE1EEEC2IJEEESt10shared_ptrIKNS_7SurfaceEERKS2_N5Eigen6MatrixIdLi1ELi1ELi0ELi1ELi1EEENSt9enable_ifIXeqplsZT_Li1EsZT0_EdE4typeEDpT_
_ZN4Acts11MeasurementINS_4Test25ExtendedMinimalSourceLinkEJLNS_22BoundParametersIndicesE0ELS3_1EEEC2IJdEEESt10shared_ptrIKNS_7SurfaceEERKS2_N5Eigen6MatrixIdLi2ELi2ELi0ELi2ELi2EEENSt9enable_ifIXeqplsZT_Li1EsZT0_EdE4typeEDpT_
```

...which are respectively displayed by c++filt as...

```
Acts::Measurement<Acts::Test::ExtendedMinimalSourceLink, (Acts::BoundParametersIndices)0>::Measurement<>(std::shared_ptr<Acts::Surface const>, Acts::Test::ExtendedMinimalSourceLink const&, Eigen::Matrix<double, 1, 1, 0, 1, 1>, std::enable_if<((0)+(1))==(0), double>::type)
Acts::Measurement<Acts::Test::ExtendedMinimalSourceLink, (Acts::BoundParametersIndices)1>::Measurement<>(std::shared_ptr<Acts::Surface const>, Acts::Test::ExtendedMinimalSourceLink const&, Eigen::Matrix<double, 1, 1, 0, 1, 1>, std::enable_if<((0)+(1))==(0), double>::type)
Acts::Measurement<Acts::Test::ExtendedMinimalSourceLink, (Acts::BoundParametersIndices)0, (Acts::BoundParametersIndices)1>::Measurement<double>(std::shared_ptr<Acts::Surface const>, Acts::Test::ExtendedMinimalSourceLink const&, Eigen::Matrix<double, 2, 2, 0, 2, 2>, std::enable_if<((1)+(1))==(0), double>::type, double)
```

The error does not occur if DemangleOptions::no_params() is set, which suggests that the problem lies within a function argument. Intuitively, the `std::enable_if` expression would be the most promizing track.

**Comment by khuey** [comment]
Yeah, we're choking at the `==(0)` in the `std::enable_if`.

llvm-cxxfilt doesn't demangle these which makes me wonder if they are in fact valid. What compiler produced these manglings?

**Comment by HadrienG2** [comment]
Clang, but a relatively old version (v10 from memory).

**Comment by khuey** [comment]
Given that they came from an old version of clang but up-to-date versions of llvm-cxxfilt (which is much better about following the name mangling spec than c++filt is) don't demangle them I'm not inclined to do anything here. If these same symbols are produced by a current version of clang then I'd be more interested.

**Comment by HadrienG2** [comment]
Thanks for the feedback. Will follow up later once I've found time to re-do the experiment with newer clang (hopefully around the end of summer).

**Comment by khuey** [comment]
Thanks for reporting, please feel free to file more issues if necessary.
