### ISSUE TITLE
Cannot demangle a handful of symbols from a Linux build of Firefox

### ISSUE THREAD

**Issue by gabrielesvelto** [gimli-rs/cpp_demangle#273]
I've used the current master branch of `cpp_demangle` on the symbols produced by a local Firefox build on my machine and found 78 that cannot be demangled. The list of affected symbols is available [here](https://drive.google.com/file/d/1H9NMRJAnv9ndDwukmvWs6HSnCyTa9Qzi/view?usp=sharing). These were generated by clang 14.0.5. As always with this kind of issues it's unclear if it's `cpp_demangle`'s fault or the symbols were mis-mangled by clang.

**Comment by gabrielesvelto** [comment]
I've fed the symbols into `llvm-cxxfilt` and the results are [here](https://drive.google.com/file/d/1RArapqvFDtac1xql8Jgckf05PQXoLrIh/view?usp=sharing). These symbols seem to share one of the two following conditions:
* They contain parameters that are function pointers qualified as `noexcept`
* They contain a `at offset <number>` component which I'm not familiar with.

Here's a couple of examples:
```
bool __gnu_cxx::__ops::_Iter_negate<int (*)(int) noexcept>::operator()<char const*>(char const*)
nsresult mozilla::extensions::AtomSet::Get<&(mozilla::extensions::WILDCARD_SCHEMES.<char const* at offset 0>)>(RefPtr<mozilla::extensions::AtomSet>&)
```

**Comment by khuey** [comment]
I did `noexcept` (the non-deprecated variants anyways).

`at offset <number>` hasn't actually made it into the spec yet: itanium-cxx-abi/cxx-abi#47
