### ISSUE TITLE
Is Travis CI still being used?

### ISSUE THREAD

**Issue by atouchet** [gimli-rs/cpp_demangle#287]
[This commit](https://github.com/gimli-rs/cpp_demangle/commit/1aad861ba189bad4e38021769b60cd93e7a65936) suggested that Travis is no longer in use however the Travis files are still in the repo. Should they be removed?

**Comment by khuey** [comment]
I would take a PR to remove them.

**Comment by atouchet** [comment]
Followup question: is coveralls still being used? .coveralls.yml appears to have been added at the same time as Travis.

**Comment by khuey** [comment]
Yeah we could remove that too.
